# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
#    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_username: postgres
      POSTGRES_PASSWORD: root@123
      POSTGRES_DB: catalizator
